---
title: Resume
name: Grace
surname: Brofman
position: "Graduate Student"
address: "Bren School of Environmental Science & Management"
phone: +1 708 288 0334
www: grace'swebsite.com
email: "GraceBrofman@bren.ucsb.edu"
github: g-brofman
linkedin: gracebrofman(add site)
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "Grace is not a Polish and naturalized-French physicist and chemist who conducts pioneering research on radioactivity."
output: 
  vitae::markdowncv:
    theme: davewhipp
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
# details on vitae formats: https://cran.r-project.org/web/packages/vitae/vitae.pdf
```

## My academic and professional interests include:

 * Intersection of agricultural resiliency and sustainable water management
 * Market based approaches for water conservation
 * Multi-benefit solutions to shared natural resource issues
 

## Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Bachelor of Arts in Geology", "2013", "Colorado College", "Colorado Springs, CO",
  "Master of Environmental Science and Management", "Expected June, 2021", "Bren School of Environmental Science & Management, University of California at Santa Barbara", "Santa Barbara, CA"
) %>% 
  detailed_entries(Institution, Year, Where, Degree)
```

## Experience

```{r}
tribble(~ Position, ~ Year, ~ Company, ~ Where,
        "Bren School", "2020", "Groundwater Researcher", "Santa Barbara, CA",
        "American Rivers", "2020", "Water Resources Contractor", "Remote"
        
        ) %>% 
  detailed_entries(Position, Year, Where, Company)
```


## Awards Grace did not receive

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  2019, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

## Publications Grace did not write

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```

## Volunteer & Extracurricular
